### ISSUE TITLE
Make help page responsive in mobile view and properly align in desktop view

### ISSUE THREAD

**Issue by QAZIMAAZARSHAD** [QAZIMAAZARSHAD/Voters-Registration-Portal#372] opened 2021-07-14 05:13 UTC
![Screenshot (52)](https://user-images.githubusercontent.com/56196640/125565076-efcb90c7-5909-46cc-9b6e-2e26e9a2093a.png)

**Comment by mayank-wadhwa-git** [comment] 2021-07-14 10:15
Could you please assign this issue to me?

**Comment by QAZIMAAZARSHAD** [comment] 2021-07-14 10:52
Under DCP?

**Comment by mayank-wadhwa-git** [comment] 2021-07-14 10:53
> Under DCP?

yes

**Comment by mayank-wadhwa-git** [comment] 2021-07-15 06:58
@QAZIMAAZARSHAD I aligned the page in desktop view but not able to recognize what is wrong in mobile view? Could you attach some screenshots

**Comment by QAZIMAAZARSHAD** [comment] 2021-07-15 07:03
> @QAZIMAAZARSHAD I aligned the page in desktop view but not able to recognize what is wrong in mobile view? Could you attach some screenshots

Check the horizontal and vertical width.

**Comment by QAZIMAAZARSHAD** [comment] 2021-07-15 07:34
![image](https://user-images.githubusercontent.com/56196640/125747534-bb59788b-811b-4509-a0b2-fd4db71b6b60.png)

**Comment by mayank-wadhwa-git** [comment] 2021-07-15 08:17
ok

**Comment by mayank-wadhwa-git** [comment] 2021-07-17 17:53
I have properly aligned in desktop view but not able to identify how to make page responsive in mobile view.
Can I PR for desktop view?

**Comment by QAZIMAAZARSHAD** [comment] 2021-07-18 01:05
No, resolve the issue completely then only make PR.

@kanak22 help @mayank-wadhwa-git.

**Comment by kanak22** [comment] 2021-07-18 16:20
> No, resolve the issue completely then only make PR.
> 
> @kanak22 help @mayank-wadhwa-git.

Sure

**Comment by QAZIMAAZARSHAD** [comment] 2021-07-22 07:55
@mayank-wadhwa-git any updates?

**Comment by mayank-wadhwa-git** [comment] 2021-07-22 08:10
No. I asked @kanak22 too but she is also not able to find what is wrong in code for mobile view. I tried everything like removed the scroll to top button commented the logo too but got nothing.
I have properly aligned the page in desktop view

**Comment by kanak22** [comment] 2021-07-22 08:21
> No. I asked @kanak22 too but she is also not able to find what is wrong in code for mobile view. I tried everything like removed the scroll to top button commented the logo too but got nothing.
> I have properly aligned the page in desktop view

I also did all these ... Still figuring out if anything else works

**Comment by QAZIMAAZARSHAD** [comment] 2021-07-22 08:23
@nlok5923 look into this.

**Comment by nlok5923** [comment] 2021-07-22 08:48
Sure i can give you the hint for resolving this issue just try to manipulate the styling of `scroll-bar div` inside the body tag as you can see in the below screen shot the issue persist when all the styling of `scroll-bar div` is applied
![image](https://user-images.githubusercontent.com/56120084/126612509-71a650b3-935a-4076-a9df-6452f6a3efed.png)

But when i removed the `overflow-y` property it just eliminates the extra padding.
![image](https://user-images.githubusercontent.com/56120084/126612616-b4be2452-ac61-4745-a593-c7e4342475c3.png)

**Comment by mayank-wadhwa-git** [comment] 2021-07-22 08:52
This is have done. the problem is in mobile view when we slide, extra white space appears about which I have no idea how to resolve that

**Comment by nlok5923** [comment] 2021-07-22 17:28
@mayank-wadhwa-git i had investigated it a bit and found that this changes are due to some of the previous merges so while having a walkthrough at some of old commits i reached the stable css for help page [here](https://gist.github.com/nlok5923/e3e6267e4b4503f76446016b8257d8d8) you can use it to spot the difference between current help page ss and previous stable css to fix this issue.

**Comment by mayank-wadhwa-git** [comment] 2021-07-23 06:27
ok sir. I will check

**Comment by mayank-wadhwa-git** [comment] 2021-07-23 06:44
The css code you provided @nlok5923 creates a horizontal scroll bar on the webpage. I implemented full code on the help page.
![Help Desk and 2 more pages - Personal - Microsoft​ Edge 23-07-2021 12_13_29](https://user-images.githubusercontent.com/68892762/126746229-99849914-cb10-4d05-b0c5-66bf517de360.png)

**Comment by QAZIMAAZARSHAD** [comment] 2021-07-23 07:10
> The css code you provided @nlok5923 creates a horizontal scroll bar on the webpage. I implemented full code on the help page.
> ![Help Desk and 2 more pages - Personal - Microsoft​ Edge 23-07-2021 12_13_29](https://user-images.githubusercontent.com/68892762/126746229-99849914-cb10-4d05-b0c5-66bf517de360.png)

Have to remove the horizontal width.

And the help page has been updated check, compare it with the actual website.

**Comment by mayank-wadhwa-git** [comment] 2021-07-23 07:35
Horizontal width appears in only mobile view and that's the problem I am not able to resolve. I downloaded the code again but still same problem persists

**Comment by nlok5923** [comment] 2021-07-23 09:02
@mayank-wadhwa-git as [this] point the help page is working fine. try to take help from it.

**Comment by mayank-wadhwa-git** [comment] 2021-07-23 09:53
ok

**Comment by aditya687** [comment] 2021-07-24 19:50
I want to make the page responsive in both mobile view and desktop view, please assign me this issue @QAZIMAAZARSHAD

**Comment by QAZIMAAZARSHAD** [comment] 2021-07-25 05:02
> I want to make the page responsive in both mobile view and desktop view, please assign me this issue @QAZIMAAZARSHAD

Solve other issues first.

**Comment by mayank-wadhwa-git** [comment] 2021-07-26 05:57
Still I am not able to resolve the issue.

**Comment by QAZIMAAZARSHAD** [comment] 2021-07-26 06:24
> Still I am not able to resolve the issue.

Fine make PR by correcting only desktop view.

**Comment by mayank-wadhwa-git** [comment] 2021-07-26 06:45
done

**Closed** 2021-08-04 13:59 UTC
Labels: DCP21, bug, good first issue, 🟪 Level0
